[build]
  functions = "netlify/functions"
  command = "node scripts/generate-firebase-config.js"

[functions]
  node_bundler = "esbuild"

# Headers for security
[[headers]]
  for = "/.netlify/functions/firebase-config"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"