# Netlify Configuration

[build]
  # Build command - generate Firebase config
  command = "chmod +x scripts/generate-firebase-config.sh && ./scripts/generate-firebase-config.sh"
  
  # Directory to publish
  publish = "."

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/js/firebase-config.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"