// Runtime access to the committed CMS marketplace dataset.
//
// The shards under data/ are generated by scripts/build-quotescout-data.mjs from
// the CMS Exchange Public Use Files. Nothing in here computes, adjusts or
// smooths a premium: every dollar figure returned is a value CMS published for
// the plan year, decoded back to the exact cent it was filed at.

import fs from 'node:fs';
import zlib from 'node:zlib';

const AGE_MIN = 18, AGE_MAX = 64;

// Where the dataset lives depends on how this module got here.
//
// Netlify bundles the function with esbuild, which inlines this file into
// netlify/functions/quotescout.mjs, so `import.meta.url` no longer points at
// this directory. `included_files` copies the data in at its repo-relative
// path under the task root instead. Unbundled (tests, local runs) the sibling
// directory is right. Try each and keep the one that actually holds the data,
// rather than guessing from an environment variable that may not be set.
export function dataCandidates(meta = import.meta.url, cwd = process.cwd(), taskRoot = process.env.LAMBDA_TASK_ROOT) {
  const rel = 'netlify/functions/lib/quotescout/data/';
  return [
    new URL('./data/', meta).href,
    new URL('./lib/quotescout/data/', meta).href,
    ...[taskRoot, cwd].filter(Boolean).map(root => new URL(rel, `file://${root.endsWith('/') ? root : `${root}/`}`).href),
  ];
}

let dir = null;
function dataDir() {
  if (dir) return dir;
  for (const candidate of dataCandidates()) {
    if (fs.existsSync(new URL('meta.json', candidate))) return (dir = candidate);
  }
  throw new Error(`Quote Scout dataset not found. Looked in: ${dataCandidates().join(', ')}`);
}

const read = name => {
  const file = new URL(name, dataDir());
  return name.endsWith('.gz') ? JSON.parse(zlib.gunzipSync(fs.readFileSync(file))) : JSON.parse(fs.readFileSync(file, 'utf8'));
};

let meta = null, zips = null, counties = null, zipStates = null;
// A warm function instance can be asked about any state, but holding all thirty
// parsed shards would be tens of megabytes for no benefit. Four covers the
// realistic working set and keeps the ceiling predictable.
const shards = new Map(), SHARD_LIMIT = 4;
const medicareShards = new Map();

export function getMeta() {
  if (!meta) meta = read('meta.json');
  return meta;
}

function shardFor(state) {
  if (shards.has(state)) { const s = shards.get(state); shards.delete(state); shards.set(state, s); return s; }
  if (!getMeta().states.includes(state)) return null;
  const shard = read(`${state}.json.gz`);
  if (shards.size >= SHARD_LIMIT) shards.delete(shards.keys().next().value);
  shards.set(state, shard);
  return shard;
}

const FIPS_STATE = { '01': 'AL', '02': 'AK', '04': 'AZ', '05': 'AR', '06': 'CA', '08': 'CO', '09': 'CT', 10: 'DE', 11: 'DC', 12: 'FL', 13: 'GA', 15: 'HI', 16: 'ID', 17: 'IL', 18: 'IN', 19: 'IA', 20: 'KS', 21: 'KY', 22: 'LA', 23: 'ME', 24: 'MD', 25: 'MA', 26: 'MI', 27: 'MN', 28: 'MS', 29: 'MO', 30: 'MT', 31: 'NE', 32: 'NV', 33: 'NH', 34: 'NJ', 35: 'NM', 36: 'NY', 37: 'NC', 38: 'ND', 39: 'OH', 40: 'OK', 41: 'OR', 42: 'PA', 44: 'RI', 45: 'SC', 46: 'SD', 47: 'TN', 48: 'TX', 49: 'UT', 50: 'VT', 51: 'VA', 53: 'WA', 54: 'WV', 55: 'WI', 56: 'WY', 60: 'AS', 66: 'GU', 69: 'MP', 72: 'PR', 78: 'VI' };
export const stateOfFips = fips => FIPS_STATE[String(fips).slice(0, 2)] || '';

// A ZIP can straddle county lines, and neighbouring counties often sit in
// different rating areas with materially different premiums. Returning the
// candidates lets the caller ask rather than silently pick one.
export function resolveZip(zip) {
  if (!zips) { zips = read('zips.json.gz'); counties = read('counties.json.gz'); }
  const list = zips[zip];
  if (!Array.isArray(list) || !list.length) return null;
  return list.map(fips => ({ fips, name: counties[fips] || fips, state: stateOfFips(fips) }));
}

/**
 * The state a ZIP belongs to, whatever the coverage. Distinguishes "we do not
 * hold data for this state" from "that is not a US ZIP code", which are very
 * different things to tell someone.
 */
export function stateOfZip(zip) {
  if (!zipStates) zipStates = read('zip-states.json.gz');
  return zipStates[zip] || '';
}

function decodeAges(encoded) {
  const parts = encoded.split('.');
  if (parts.length !== AGE_MAX - AGE_MIN + 1) return null;
  const out = new Array(parts.length);
  let value = 0;
  for (let i = 0; i < parts.length; i++) {
    const delta = parseInt(parts[i], 36);
    if (!Number.isSafeInteger(delta)) return null;
    value = i === 0 ? delta : value + delta;
    if (!Number.isSafeInteger(value) || value < 0) return null;
    out[i] = value;
  }
  return out;
}

function servesCounty(area, fips, zip) {
  if (!area) return false;
  if (area.all) return true;
  if (!area.c.includes(fips)) return false;
  // A partial county is only sold in the ZIPs the issuer listed for it.
  const partial = area.z?.[fips];
  return !partial || partial.includes(zip);
}

/**
 * Every plan a single adult can buy in this county, priced at their exact age.
 * `dental` selects the dental-only market; medical and dental are separate
 * purchases on the Marketplace and are never mixed into one ranking.
 */
export function plansFor({ state, fips, zip, age, tobacco, dental = false }) {
  const shard = shardFor(state);
  if (!shard) return null;
  if (!Number.isInteger(age) || age < AGE_MIN || age > AGE_MAX) return null;
  const ratingArea = shard.ra[fips] ?? shard.rz[String(zip).slice(0, 3)];
  if (!ratingArea) return null;

  const out = [];
  for (const [id, plan] of Object.entries(shard.p)) {
    if (!!plan.d !== !!dental) continue;
    if (!servesCounty(shard.sa[plan.a], fips, zip)) continue;
    const encoded = shard.r[id]?.[ratingArea];
    if (!encoded) continue;
    // A tobacco surcharge only applies where the issuer filed tobacco rates.
    // Where they filed a single rate, that rate is the price either way.
    const vector = decodeAges(tobacco && encoded.t ? encoded.t : encoded.n);
    if (!vector) continue;
    const premium = vector[age - AGE_MIN];
    if (!Number.isSafeInteger(premium) || premium <= 0) continue;
    out.push({
      id,
      name: plan.n,
      issuer: plan.i,
      metal: plan.m,
      planType: plan.t,
      premium,
      deductible: plan.ded ?? null,
      outOfPocket: plan.moop ?? null,
      deductibleCombined: !!plan.dedCombined,
      hsaEligible: !!plan.hsa,
      multipleTiers: !!plan.tiers,
      nationalNetwork: !!plan.national,
      dental: !!plan.d,
      ratingArea,
      tobaccoRated: !!encoded.t,
    });
  }
  return { ratingArea, plans: out };
}

/**
 * Every Medicare Advantage and standalone Part D plan sold in this county.
 *
 * Medicare premiums do not vary with age, sex or tobacco: a plan costs what it
 * costs where it is sold. That is why this takes a county and nothing else,
 * and why the shopper is only ever asked for a ZIP.
 *
 * Special-needs plans are excluded at build time: they are restricted to people
 * who qualify by dual eligibility, institutional status or a named chronic
 * condition, so listing them beside open-enrollment plans would show prices
 * most people cannot buy.
 */
export function medicarePlansFor({ state, fips }) {
  let shard = medicareShards.get(state);
  if (shard === undefined) {
    try { shard = read(`medicare/${state}.json.gz`); }
    catch { shard = null; }
    if (medicareShards.size >= SHARD_LIMIT) medicareShards.delete(medicareShards.keys().next().value);
    medicareShards.set(state, shard);
  }
  if (!shard) return null;
  const indexes = shard.c[fips];
  return {
    year: shard.year,
    region: shard.region,
    // Advantage plans are county-level; standalone drug plans are sold across a
    // whole PDP region, which is the state here.
    advantage: (indexes || []).map(i => shard.p[i]).filter(Boolean),
    drug: shard.d,
  };
}

/**
 * The second-lowest-cost silver premium for this person, which is the figure
 * the Marketplace uses as the benchmark for premium tax credits. It is derived
 * entirely from the published rates above, so it is a real number rather than
 * an estimate; the size of anyone's actual credit still depends on household
 * income and family composition, which Quote Scout never asks for.
 */
export function benchmarkSilver(plans) {
  const silver = plans.filter(p => p.metal === 'Silver' && !p.dental).map(p => p.premium).sort((a, b) => a - b);
  return silver.length >= 2 ? silver[1] : silver[0] ?? null;
}
