// Team data for different leagues

export const TEAMS_DATA = {
  'Premier League': [
    'Arsenal',
    'Aston Villa',
    'Brighton & Hove Albion',
    'Burnley',
    'Chelsea',
    'Crystal Palace',
    'Everton',
    'Fulham',
    'Liverpool',
    'Luton Town',
    'Manchester City',
    'Manchester United',
    'Newcastle United',
    'Nottingham Forest',
    'Sheffield United',
    'Tottenham Hotspur',
    'West Ham United',
    'Wolverhampton Wanderers',
    'Brentford',
    'Bournemouth',
  ],
  'La Liga': [
    'Athletic Bilbao',
    'Atlético Madrid',
    'Barcelona',
    'Cádiz',
    'Celta Vigo',
    'Getafe',
    'Girona',
    'Granada',
    'Las Palmas',
    'Mallorca',
    'Osasuna',
    'Rayo Vallecano',
    'Real Betis',
    'Real Madrid',
    'Real Sociedad',
    'Sevilla',
    'Valencia',
    'Villarreal',
    'Alavés',
    'Almería',
  ],
  Bundesliga: [
    'FC Augsburg',
    'Bayer Leverkusen',
    'Bayern Munich',
    'VfL Bochum',
    'Borussia Dortmund',
    'Borussia Mönchengladbach',
    'SV Darmstadt 98',
    'Eintracht Frankfurt',
    'SC Freiburg',
    'FC Heidenheim',
    'TSG Hoffenheim',
    'FC Köln',
    'RB Leipzig',
    'Mainz 05',
    'Union Berlin',
    'VfB Stuttgart',
    'Werder Bremen',
    'VfL Wolfsburg',
  ],
  'Serie A': [
    'Atalanta',
    'Bologna',
    'Cagliari',
    'Empoli',
    'Fiorentina',
    'Frosinone',
    'Genoa',
    'Hellas Verona',
    'Inter Milan',
    'Juventus',
    'Lazio',
    'Lecce',
    'AC Milan',
    'Monza',
    'Napoli',
    'Roma',
    'Salernitana',
    'Sassuolo',
    'Torino',
    'Udinese',
  ],
  'Ligue 1': [
    'AC Ajaccio',
    'Angers',
    'Brest',
    'Clermont',
    'Le Havre',
    'Lens',
    'Lille',
    'Lorient',
    'Lyon',
    'Marseille',
    'Metz',
    'Monaco',
    'Montpellier',
    'Nantes',
    'Nice',
    'Paris Saint-Germain',
    'Reims',
    'Rennes',
    'Strasbourg',
    'Toulouse',
  ],
  'National Teams': [
    'Argentina',
    'Australia',
    'Belgium',
    'Brazil',
    'Canada',
    'Colombia',
    'Croatia',
    'Denmark',
    'England',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'Mexico',
    'Morocco',
    'Netherlands',
    'Poland',
    'Portugal',
    'Senegal',
    'Serbia',
    'South Korea',
    'Spain',
    'Switzerland',
    'Ukraine',
    'United States',
    'Uruguay',
    'Wales',
  ],
};
